# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.
 # - name: Taks
  #   url: '#tasks'
  #   weight: 35
main:
  - name: Home
    url: /
    weight: 10
  - name: About
    url: '#info'
    weight: 20
  - name: Download
    url: '#portfolio'
    weight: 30
  - name: Evaluation
    url: '#evaluation'
    weight: 40
  - name: Citation
    url: '#citation'
    weight: 50
  - name: Contact
    url: '#contact'
    weight: 60
  # - name: Task
  #   url: '#task'
  #   weight: 60
  # - name: Posts
  #   url: '#posts'
  #   weight: 70
  
  # - name: Leaderboard
  # url: '#leaderboard'
  # weight: 40